### ISSUE TITLE
failed to run SendNotification: failed to write Slack message: failed to unmarshal templating JSON

### ISSUE THREAD

**Issue by dhruvmalik13** [simplifi/terraform-google-cloud-build-slack-notifier#7]
After applying terraform and once the cloud build image gets built successfully, I'm unable to receive slack notifications and here is the below error:

```
DEFAULT 2023-04-21T07:15:17.598870Z I0421 07:15:17.598745 1 main.go:80] sending Slack webhook for Build "1c955b29-fd76-44c9-9215-5667e5c876ed" (status: "SUCCESS")
DEFAULT 2023-04-21T07:15:17.598891Z E0421 07:15:17.598798 1 notifiers.go:549] failed to run SendNotification: failed to write Slack message: failed to unmarshal templating JSON: unexpected end of JSON input
```

As per the Google docs - https://cloud.google.com/build/docs/configuring-notifications/configure-slack#configuring_slack_notifications , on point 7- for slack notifier configuration file, it contains the below template param which has the JSON template path for the slack message to be sent.

```
    template:
      type: golang
      uri: gs://example-gcs-bucket/slack.json

## The uri field references the slack.json file. This file contains a JSON template hosted on Cloud Storage and represents your notification message to your Slack space.
```

While looking at the `cloud_build_notifier_config`  in the `main.tf` file - https://github.com/simplifi/terraform-google-cloud-build-slack-notifier/blob/main/main.tf#L125  I don't see the template being passed, I think it needs the above template param along with the JSON template URI.

Here are the environment details:
```
Terraform v1.4.5
+ provider registry.terraform.io/hashicorp/google v4.20.0
+ provider registry.terraform.io/hashicorp/google-beta v4.62.1
+ provider registry.terraform.io/hashicorp/random v3.5.1
```
